### PR TITLE
Fix subdomain email address error in email_pwned module

### PR DESCRIPTION
**Pull request by adviksinghania**
This fixes issue #158 
Please review the changes

### CODE REVIEW

**Comment by saeeddhqan** [comment]
Check it out

**Comment by adviksinghania** [comment]
I'm getting this error on every query...
```bash
OWASP Maryam(v2.0.0): Open-source Intelligence Framework.
To show the framework help, run 'help' command.
[maryam][default] > email_pwned -e sam@learn.mailgun.com
[*] [PAWNED] Searching for pwning...
[!] Email_PwnedCodeError: list index out of range.
[maryam][default] > 

```

**Comment by saeeddhqan** [comment]
Again, check the amendments. If you got an error, solve it if you can. the error happens in the module_run function.

**Comment by k4u5h1k** [comment]
@saeeddhqan remember how in my phone number search module you told me not to check the input phone number validity with regex and let the api handle it.   
I feel like it is way better to do the same here.

**Comment by z3y50n** [comment]
I am getting this error some times
image

**Comment by adviksinghania** [comment]
If the email is not pawned, the module outputs an empty table like this...
```bash
[maryam][default] > email_pwned -e sam@mail.hive.co
[*] [PAWNED] Searching for pwning...

  +-------------------+
  |      breaches     |
  +-------------------+
  | breaches | pastes |
  +-------------------+
  +-------------------+


  +-------------------+
  |       pastes      |
  +-------------------+
  | breaches | pastes |
  +-------------------+
  +-------------------+

```

Wouldn't it be better to output something to the user like "The email has not been pawned." if both the tables are empty ?
Besides that, I think the bug is resolved.

**Comment by saeeddhqan** [comment]
the empty table aims to say that

**Pull request merged**
