### PR TITLE
Created GUI with Angular and Django

### PR DESCRIPTION
**Pull request by FoxSinOfGreed1729**
#### Changes

- Added GUI for OWASP Maryam
- Used Angular for Frontend
- Used Django for Backend
- Currently only supports one module - crawl_pages

#### To Do

- Add support for all modules
- Improve the output
- Refine logic to process display

#### Checklist

- [x] I have read the Contribution & Best practices Guideline.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The acceptance, integration, unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by saeeddhqan** [comment]
@DigvijayBhosale1729 before making GUI, you are supposed to create an issue to describe the work. I cannot accept this pr: codes are huge, and we do not have a plan for a regular GUI.
Instead, I wanted to use vis.js to show the number of clusters by clustering module and things like that. therefore, If you want to contribute, add only a web page the user can search a term and cluster documents by clustering module and plot the results with vis.js. exactly like carrot2(google it). I have a demo code for it if you want I can share it. we have everything but a front-end page.

**Comment by FoxSinOfGreed1729** [comment]
@saeeddhqan 
Thanks for being patient with me.
I read that a web UI was in the to do list in readme.md of this project, hence the PR. 
I'll check out Carrot2 and try to make a web page using vis.js.

**Comment by moshaad7** [comment]
@saeeddhqan  can you share the demo code that you have mentioned in **I have a demo code for it if you want I can share it. we have everything but a front-end page.**

**Comment by saeeddhqan** [comment]
attached. @moshaad7
[clustering.html.txt](https://github.com/saeeddhqan/Maryam/files/7640648/clustering.html.txt)

**Pull request closed without merging**
