### PR TITLE
Improved Setup.py. Added Uninstaller

### PR DESCRIPTION
**Pull request by FoxSinOfGreed1729**
#### Resolves - 
- Earlier, Setup.py installed pip dependencies using hard coded values.
- Now, Setup.py installed pip dependencies from requirements file
- Added uninstall.sh that uninstalls Maryam for user. (Including all files, folders and python dependencies)

#### Checklist

- [x] I have read the Contribution & Best practices Guideline.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The acceptance, integration, unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by saeeddhqan** [comment]
Add uninstall.sh to the make. isn't it better?
And about requirements, I did this for previous versions. but whenever pip tries to install requirements, it cannot find the requirements file and returns an error.

**Comment by FoxSinOfGreed1729** [comment]
> Add uninstall.sh to the make. isn't it better? And about requirements, I did this for previous versions. but whenever pip tries to install requirements, it cannot find the requirements file and returns an error.

Thank you sir for replying and approving.

I'll change the makefile uninstalll command to this
```
uninstall:  ## Uninstall package
	pip uninstall maryam
	bash uninstall.sh
```
Hope thats what is required
The name of requirements file is `requirements` as opposed to the usual `requirements.txt`. That may be the reason for the FileNotFound error may lie there. I've tried this code on my machine and it can access the requirements file and install requirements.

**Comment by saeeddhqan** [comment]
It seems you used 4-spaces instead of a tab in the setup.py. Change it; then I shall merge.

**Comment by FoxSinOfGreed1729** [comment]
> It seems you used 4-spaces instead of a tab in the setup.py. Change it; then I shall merge.

I tried changing the 4 spaces with tab but GitHub says that its the same text and not allowing to change file. Could you please tell me how i can check if it's 4 spaces or a tab because i don't know how to differentiate between the two right now.

**Comment by saeeddhqan** [comment]
By using sublime-text, tab-size > convert indentations to tab

**Pull request merged**
