### PR TITLE
Create quora.py

### PR DESCRIPTION
**Pull request by theamanrawat**
### Quora Search in Maryam Search module

Screenshot (38)

after adding this Maryam can also able to search profiles and links in Quora related to the given query which might be useful in information gathering for any person in Quora because in this platform we are able to get questions and answers asked or given by the person.

Thank you

### CODE REVIEW

**Comment by saeeddhqan** [comment]
Aman,

There is some note that you should know about it.

- Firstly, the author name and module name should be your module version and your name.
- For quora, you can use other search engines like yahoo, yippy, etc. So add these engines to the support engines to get more results.
- Another feature that you can add to this module is to extract the title from the URL and show the title with the URL together, like https://www.quora.com/How-should-I-start-learning-Python-1 with the title "How Should I Start Learning Python 1"

Try to add these points and let me know.

**Review by theamanrawat — COMMENTED** [review]
Hi Saeed,

:white_check_mark: Added my name as author name and also changed version

:white_check_mark: Added search engines such as google, yahoo, bing and yippy for more results.

:white_check_mark: added a feature to extract the title from the URL and show the title with the URL together

Screenshot (39)

Here I am fetching title also and showing title and link together.

Thank you

**Comment by theamanrawat** [comment]
I've also fixed an error in yippy search

Screenshot (40)

yippy.py is giving this error because limit and count was not defined so I fixed it.

**Comment by saeeddhqan** [comment]
Done

**Pull request merged**
