### PR TITLE
Add reverse dns search option

### PR DESCRIPTION
**Pull request by z3y50n**
I have added the option to get the **hostname** by giving the ip address as `domain` parameter.

I would like some suggestions regarding the code format and placement as well as the output. An example usage is shown below.

image

### CODE REVIEW

**Comment by saeeddhqan** [comment]
Can you do it for a list of domains? it would be more efficient.

**Comment by z3y50n** [comment]
Added search for multiple ips. More work can be done to display the  results in a nicer way

**Comment by saeeddhqan** [comment]
I'll change the output format and using the reverse option as domain names instead of the domain.
Thank you!

**Comment by saeeddhqan** [comment]
Don't use print directly in the modules. Instead, use _self.output(msg, color)_, _self.alert(msg)_, _self.error(msg)_, and _self.verbose(msg)_.

Two new sources has been added. The output format has been changed and it can read ips from a file.

**Pull request merged**
