### PR TITLE
Added Downloader util class 

### PR DESCRIPTION
**Pull request by rishi23root**
In the form added #227 

Fixes #

#### Resolves
a new feature is added

#### Changes

- created core/util/downloader.py to download the data by URL or request's response
  - can be used to get a single URL or multiple URLs
  - can limit by type of context 
- created modules/osint/webget.py to use core/util/downloader.py 
- and some small changes in the core/initial.py file.

#### Checklist

- [X] I have read the Contribution & Best practices Guideline.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [X] The acceptance, integration, unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by saeeddhqan** [comment]
It should be in the crawler as an option. it's very simple. and give me time to finish the Maryam arch, then I merge it.

**Comment by saeeddhqan** [comment]
resolve conflicts and add an option to the crawler for downloading specified file endpoints.

**Comment by rishi23root** [comment]
> resolve conflicts and add an option to the crawler for downloading specified file endpoints.

1. Done
2. It is already there with flag -g (I also clarified a bit more )

**Comment by saeeddhqan** [comment]
I mean the crawler module. e.g `crawler -d blackhat.com -l 5 --save pdf,docx`. this feature is easy. just get results from web_scrap and check out the `output['media']` URLs and find the specified files(pdf, docx) and download them.

**Pull request closed without merging**
