### PR TITLE
Code relocated under maryam/, added setup.py

### PR DESCRIPTION
**Pull request by k4u5h1k**
#### Resolves
- Changes how core looks for modules (current method does not work after `pip install .`). 
- Fixes `Version check failed` error when maryam is run from outside git directory.

#### Changes
- All code and assets have been relocated under src/.
- initial.py uses basedir instead of looking for modules under sys.path[0].
- Adds a block in initial.py to fix `Version check failed error`.

#### Checklist

- [X] I have read the Contribution & Best practices Guideline.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [ ] The acceptance, integration, unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by k4u5h1k** [comment]
## NOTE:
- **Not fit to merge yet. Requires further testing.**
- Pypi does not allow uploading more than once with the same version name. Therefore I will change version to 2.1.0 once testing is over

**Comment by necrose99** [comment]
could pull to a dev branch as to not touch main....

python/....../maryam :  subfolders  maryam/core  maryam/data  ./marya/marayon.py   

expected setup.py 
cp ./Maryam/* to python install  ie /usr/lib/python3.9/**Maryam**/ 
 , make pyc/pyo eggs/wheels etc.. 
this is standard typical conventional wisdom  unless otherwise required. 

windows freeze mayam.py to exe ie pyinstaller or etcc.. however another day... for improvements... or further milestones.. 

https://pypi.org/project/setupcfg-generator/ 
https://pypi.org/project/setup2poetry/ for toml 
https://pypi.org/project/setup-freeze/
https://pypi.org/project/setuppy-generator/ 
https://www.jetbrains.com/help/pycharm/creating-and-running-setup-py.html

https://pyscaffold.org/en/latest/migration.html tends to require anaconda/ or etc ... 
Gentoo wise or otherwise  ln- s maryam.py /usr/bin/maryam  or [eselect-python](https://packages.gentoo.org/packages/app-eselect/eselect-python ) ;   [python-exec](https://packages.gentoo.org/packages/dev-lang/python-exec) dose the automagic symlinking...  per python ie 3.9 , 3.10 3.x-newer 4.0 ?? etc... 



my hope is to make an ebuild script to automate gentoo linux  installs...

**Comment by k4u5h1k** [comment]
> expected setup.py
> cp ./Maryam/* to python install ie /usr/lib/python3.9/**Maryam**/

Yes I have reworked the architecture so it does exactly that now.
Used [https://github.com/laramies/theHarvester](https://github.com/laramies/theHarvester) as reference. 

Currently only focused on a simple, tested, base setup.py. Will work on your suggested improvements once that is done

**Comment by necrose99** [comment]
https://github.com/saeeddhqan/Maryam/pull/209
https://github.com/pentoo/pentoo-overlay/blob/master/net-analyzer/theHarvester/theHarvester-3.2.3.ebuild
esiliy re-achitected to buid maryam 
mainly  for making ebuild @pentoo  setup.py
for others https://pypi.org/project/stdeb/  for kali 
https://pypi.org/project/pyp2rpm/ 
 

however improved on idea good deal.

**Comment by k4u5h1k** [comment]
The problem with an ebuild for pentoo is that I can't test it. Also do not have kali.  
@necrose99 can we merge this now (or after a little more testing) and ask someone else from  
your community for a pentoo build?

**Comment by necrose99** [comment]
@k4u5h1k  i dont have kali ,  however the stdeb package you can make a deb for debian or Ubuntu.... 
or the rpyp2rpm package if on centos or the like... 
as for pentoo/Gentoo , packaging python ie routersploit , w/o setup.py my inital ebuild was supper cludgy ..
[pypi2pkgbuild](https://pypi.org/project/pypi2pkgbuild/) for arch fans

with a setup.py makes for much easier packaging.. theHarvester-3.2.3.ebuild or alike is easy to move in required deps re-save pull... 

I'll be happy to Pull for for a new package to pentoo the moment the setup.py is official.....
and for the local Dallas OWASP cominity :-)

**Comment by k4u5h1k** [comment]
Alright great. Still want to do a little more testing although haven't noticed any issues yet.

**Comment by saeeddhqan** [comment]
Done.

**Pull request closed without merging**
