### PR TITLE
[WIP] Adding Sources to the username_checker.json

### PR DESCRIPTION
**Pull request by prince-7**
Added More sources, Adding the error message for each source remaining.

### CODE REVIEW

**Comment by prince-7** [comment]
Don't merge yet

**Comment by saeeddhqan** [comment]
Wow. It's huge. I think you need to have a change in the module: There's no need to print all of the failed efforts.
What do you think?

**Comment by prince-7** [comment]
> Wow. It's huge. I think you need to have a change in the module: There's no need to print all of the failed efforts.
> What do you think?

Yes, I think that would be the right thing, will do that in this PR, along with compressing the JSON file.

**Comment by saeeddhqan** [comment]
Did you check this? https://raw.githubusercontent.com/WebBreacher/WhatsMyName/master/web_accounts_list.json

**Comment by prince-7** [comment]
This is ready for merge and closing #52

**Pull request merged**
