### PR TITLE
username_search now works when invoked from outside cloned dir

### PR DESCRIPTION
**Pull request by k4u5h1k**
Previously `username_checker` did not work when executed from another directory because the username_checker json path was appended to `os.cwd`.

This was fixed using
```
from os.path import dirname as up 
project_root = up(up(up(__file__)))
filepath = os.path.join(project_root, 
                       'data', 
                       'username_checker.json')
```

Also,
`data = json.loads(handle.read())`
was replaced with
`data = json.load(handle)`

Closed the previous PR to fix my editor's tab settings and recommit

### CODE REVIEW

**Comment by k4u5h1k** [comment]
`dnsbrute` and `tldbrute` have this issue as well.  
Shall fix them.

**Comment by saeeddhqan** [comment]
Fix them with this PR. Again, your PR has a tab error.

**Comment by k4u5h1k** [comment]
Done.
Added
```
ROOT = up(up(up(os.path.realpath(__file__))))
os.path.join(ROOT, 'data', 'tlds.txt')
```
in `tldbrute`
Same was repeated for `dnsbrute`

**Comment by saeeddhqan** [comment]
@z3y50n will check the changes and merge the PR.

**Comment by z3y50n** [comment]
I was planning to push some minor fixes I found. I will push them directly to master

**Pull request merged**
