### PR TITLE
Adding SPYSE Tools

### LINKED ISSUE #240: [New Feature] Adding Spyse APIs module and util class
Spyse has got many API which can provide lots of info about a domain. They can be used via Cloudscraper.

### PR DESCRIPTION
**Pull request by vikas-kundu**
Fixes #240 

#### Resolves
Adds all the tools present on the Spyse website

#### Changes

- util/search/spyse.py
- search/spyse.py

#### Checklist

- [x] I have read the Contribution & Best practices Guideline.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The acceptance, integration, unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by vikas-kundu** [comment]
I will be working on this module to add all the tools of spyse one by one. Meanwhile, there is a lot of info that is obtained from the results. So while I am adding tools, it could be of great help if someone could write parse function (to return only relevant info from all the data) of each of the tool in the util/search/spyse.py. See line 102 and 105 of util class. Parsing functions needed at present:
- whois_parser (parse info from whois data)
- company_parser (parse info from company data)

**Comment by saeeddhqan** [comment]
I cannot evaluate your pr for now.

**Comment by vikas-kundu** [comment]
> I cannot evaluate your pr for now.

It's ok, it will take me a few weeks to complete it.

**Comment by vikas-kundu** [comment]
@saeeddhqan I have finished the PR for these 2 tools, you can do a review if possible. Here is a gif of the module: https://asciinema.org/a/Z39EB1qio63qdcqUBpltIVXZe

**Pull request closed without merging**
