### PR TITLE
Added a new module which scraps for pwned email fusing cloudscraper

### PR DESCRIPTION
**Pull request by vikas-kundu**
This module will use xmlHTTP api of haveibeenpwned.com to list any breaches and pastes of an email if available. Since the endpoint is Cloudflare protected, cloudscraper has been used and added to requirements. 

This module will list the breach domain and breach name for an email.
For pastes, it will list Id, Source and Title of the public paste for an email.

### CODE REVIEW

**Comment by saeeddhqan** [comment]
Can you show me a gif?
I also can't see any module.

**Comment by vikas-kundu** [comment]
https://asciinema.org/a/JE4S9MhFJxFQRbUAngvIq82ZO

**Comment by vikas-kundu** [comment]
@saeeddhqan sorry looks like an error on my part. This is my first pull request so messed up. Will retry.

**Comment by vikas-kundu** [comment]
Please delete this request so that i can issue a new one.

**Pull request closed without merging**
