### PR TITLE
setup.py skeleton

### PR DESCRIPTION
**Pull request by necrose99**
for gentoo / pentoo.org setup.py make far easier via ebuild , and for arch via pkgbuild
wheel2deb /py2deb pypi2rpm/pyp2rpm
easier linux distro , py2exe2msi windows..

add setup.py skell / tox skell 

could stick on dev/etc branch if you dont care to clobber main yet. 

Dallas OWASP.. 

Any rate hoping package to @pentoo shortly

### CODE REVIEW

**Comment by saeeddhqan** [comment]
It seems setup.py is a binary file(for github) and I cannot review/edit the code.

**Comment by saeeddhqan** [comment]
@necrose99 what is the next plan?
It's better to announce it along with the new version, which supports document classification.

**Comment by necrose99** [comment]
@saeeddhqan if the setup.py functions i will move to add a @pentoo /@gentoo package. 
Maryam , a FLEXIBLE modular OWASP OSINT utility. 
As both a 9999 package (git clone/distutils-r1.eclass) 
and version'd 
https://pypi.org/project/setup2poetry/ update toml file.. 
I mearly useed a setup.py generator, 
(Pyscaffold is the overkill in that.. but great for starting a project from scratch) 
Much i need to learn over my novice python.. crappie...  
But 30k foot Proj. Mng. Veiws see the lt success of this by far.

Well managed OSINT TOOLS  via development..  that dont turn commercialized...  or give up... are a rarity. 

Anyone in OWASP,  including my chapter Dallas-Fort Worth,  can move to eat  test the app. Via @pentoo linux. And ill make mention of this also via @OWASPDallas Twitter... 

https://github.com/pentoo/pentoo-overlay

https://github.com/pentoo/pentoo-overlay/tree/master/net-analyzer/honeypots 
Also a pypi script. 
:-)

Pypi you can likewise publish... , as a working setup.py makes everyone happy 
As for docker and 📊 etc.. should make life easier.  As most distributions can use pip without breaking stuff..

https://pypi.org/project/stdeb/ 
Python setup.py build_deb ... or similar.. 
For debian or Kali linux etc..

**Comment by saeeddhqan** [comment]
@necrose99 we have a problem with setup.py in the #233 pr. whenever we run `pip install maryam`, it makes a module called core, which is the maryam core. It shouldn't be like that, right? what should we do?

**Comment by saeeddhqan** [comment]
Check out the new version.

**Comment by necrose99** [comment]
#233 supperseeds

**Pull request closed without merging**
