### PR TITLE
updated requirements

### PR DESCRIPTION
**Pull request by Grogu22**
Fixes #

#### Resolves
updated the ```requirements``` file, now dependency conflicts need not be fixed manually

#### Changes

-  Updated the requirements
-  Now simply install dependencies in your virtual environment using ```pip install -r requirements```  

#### Checklist

- [x] I have read the Contribution & Best practices Guideline.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The acceptance, integration, unit tests pass locally with my changes 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by saeeddhqan** [comment]
Your file is a binary file.

**Comment by Grogu22** [comment]
Ok, making it .txt

**Comment by Grogu22** [comment]
I[image: image.png]
I can view it tho 😶

**Comment by Grogu22** [comment]
Maybe see ```view file```  ?

**Comment by Grogu22** [comment]
@saeeddhqan resolved issue..

**Pull request merged**
