### PR TITLE
Adding iris_cluster module

### LINKED ISSUE #258: Clustering Module only accepts .json file but not JSON object .
While developing a GUI for ( Iris Search + Cluster), I was using Maryam's webAPI module and found out that we need to save the result of Iris into a .JSON file and then Call Cluster API supplying JSON file.

**Problems** 
- This isn't a scalable solution when deploying web app (because we have to create JSON files for each user and for each query). 

**Proposed Solution**
- Have a unified api which can supply the result of Iris directly to Cluster as JSON object to process data at server side 

Please assign this task to me, 
After completing this task I will be developing a React UI which will consume this API and Layout visualization of Clusters

### PR DESCRIPTION
**Pull request by moshaad7**
Fixes #258 

#### Resolves
Resolves the problem of needing to store result of iris_module in a .json file and then supplying it to cluster_module

#### Changes

- Refactored code in _core/web/api.py_ file by creating two functions `set_framework_options` and `run_module_api` and moved them to _core/initial.py_
- Added an option for directly supplying json object to `cluster_module`
- Added a new module called **iris_cluster** which takes a query and run iris module followed by cluster module and return both results

#### Checklist

- [x] I have read the Contribution & Best practices Guideline.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The acceptance, integration, unit tests pass locally with my changes 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### How to use iris_cluster module  
- web api example: `http://127.0.0.1:1313/api/modules?_module=iris_cluster&q=owasp maryam`
- cui example: `maryam -e iris_cluster -q "owasp maryam"`

### CODE REVIEW

**Comment by saeeddhqan** [comment]
Instead of trying to run the cluster module in your module, use self.cluster, exactly like the cluster module. Please have a look on this page for your code style: https://github.com/saeeddhqan/Maryam/wiki/Development-Guide#code-style

**Comment by moshaad7** [comment]
Thank you for the feedback @saeeddhqan , I have commited the above mentioned changes

**Comment by saeeddhqan** [comment]
don't change initial. Instead run iris module with `self.opt_proc('iris', args='-q $query --api', output='web_api')` it should return iris results in a json format. replace $query with the given query.

**Comment by moshaad7** [comment]
Thank you for the guidance @saeeddhqan , I have commited the above mentioned changes

**Comment by saeeddhqan** [comment]
You've changed four files. revert all except your module. also add save_gather at the end of module_api module, like every module in Maryam, we need to run save_gather. after that, show me a screenshot from the output.

**Comment by moshaad7** [comment]
Hi saeed I have reverted all files except iris_cluster module and I have added save_gather also.
But it's still showing four files changes with a change of **No new line at the end of file** for reverted files

### Screenshots:

**web api**

Screenshot 2021-12-14 at 11 45 56 PM

Screenshot 2021-12-14 at 11 46 14 PM

**CUI**
- Iris Results

Screenshot 2021-12-14 at 11 46 28 PM

- Cluster Results

Screenshot 2021-12-14 at 11 46 45 PM

**Comment by saeeddhqan** [comment]
Now, start working on your UI.

**Comment by moshaad7** [comment]
Ok @saeeddhqan , thank you

**Comment by moshaad7** [comment]
I am facing issues in reverting files and getting error "**No new line at the end of file** ", That's why closing this PR, will Raise a new PR with only iris_cluster_module

**Pull request closed without merging**
