### PR TITLE
Format maryam script

### PR DESCRIPTION
**Pull request by adviksinghania**
Format maryam and core/base.py script and removed unused imports ```errno```, ```random``` and ```Pool``` from multiprocessing.
For issue #77

### CODE REVIEW

**Comment by saeeddhqan** [comment]
Will be done by the new version.

**Comment by adviksinghania** [comment]
Okay. Thanks.
Can I work on a linting script before the new version, so that it'll help future contributors ?

**Comment by saeeddhqan** [comment]
Some have been fixed.
Check the new version.
It is not good to replace \t with 4 space.

**Comment by saeeddhqan** [comment]
It is not qualified.

**Pull request closed without merging**
